import type {
  HistoryEntry,
  TranslationEngine,
  TranslationResult,
  TranslationSource,
} from '@/types';

import type { TranslationRow } from './schema';

/**
 * Converts between the SQL row shape and the domain entry.
 *
 * Rows are validated rather than cast. A database file can be older than the
 * build reading it, restored from a backup, or corrupted, and a single bad row
 * should cost that one row — not the whole history screen.
 */

const ENGINES: readonly TranslationEngine[] = ['online', 'offline', 'mock'];
const ORIGINS: readonly TranslationSource[] = ['text', 'camera', 'voice', 'clipboard'];

function asEngine(value: unknown): TranslationEngine {
  return ENGINES.includes(value as TranslationEngine) ? (value as TranslationEngine) : 'online';
}

function asOrigin(value: unknown): TranslationSource {
  return ORIGINS.includes(value as TranslationSource) ? (value as TranslationSource) : 'text';
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === 'string' && value.length > 0;
}

/**
 * Maps one row, or returns undefined when it cannot be trusted.
 *
 * The required fields are the ones the UI would otherwise render as `undefined`
 * or use to build a broken link: an entry with no id, no text or no languages
 * is not a translation anyone can act on.
 */
export function toHistoryEntry(row: unknown): HistoryEntry | undefined {
  if (typeof row !== 'object' || row === null) return undefined;
  const record = row as Partial<TranslationRow>;

  if (
    !isNonEmptyString(record.id) ||
    typeof record.source_text !== 'string' ||
    typeof record.translated_text !== 'string' ||
    !isNonEmptyString(record.source_language) ||
    !isNonEmptyString(record.target_language)
  ) {
    return undefined;
  }

  const createdAt = Number(record.created_at);

  return {
    id: record.id,
    sourceText: record.source_text,
    translatedText: record.translated_text,
    sourceLanguage: record.source_language,
    detectedLanguage: isNonEmptyString(record.detected_language)
      ? record.detected_language
      : undefined,
    targetLanguage: record.target_language,
    engine: asEngine(record.engine),
    origin: asOrigin(record.origin),
    // A missing or non-numeric timestamp sorts last rather than as 1970.
    createdAt: Number.isFinite(createdAt) ? createdAt : 0,
    isFavorite: Number(record.is_favorite) === 1,
  };
}

/** Maps a result set, dropping rows that cannot be trusted. */
export function toHistoryEntries(rows: readonly unknown[]): HistoryEntry[] {
  const entries: HistoryEntry[] = [];
  for (const row of rows) {
    const entry = toHistoryEntry(row);
    if (entry) entries.push(entry);
  }
  return entries;
}

/**
 * Builds the row for a new history record.
 *
 * The id is generated by the caller and is deliberately *not* the translation
 * result's id: a cached result is replayed with the same id, but each time the
 * user presses Translate it is a separate event and deserves its own row.
 */
export function toTranslationRow(
  id: string,
  result: TranslationResult,
  isFavorite = false,
): TranslationRow {
  return {
    id,
    source_text: result.sourceText,
    translated_text: result.translatedText,
    source_language: result.sourceLanguage,
    detected_language: result.detectedLanguage ?? null,
    target_language: result.targetLanguage,
    engine: result.engine,
    origin: result.origin,
    is_favorite: isFavorite ? 1 : 0,
    // Epoch milliseconds: absolute, UTC by definition, and formatted only at
    // the UI layer so the displayed time follows the device.
    created_at: result.createdAt,
  };
}
